[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Madhava HPC"
authors = [{name = "sajil", email = "iamsajil7@gmail.com"}]
dynamic = ["version", "description"]
